sim:
  numEnv: 4096
  #number of racing agents per env
  numAgents: 1
  dt: 0.02 #[s] # If using this with TRI dynamics model, this must be 0.02 to match the refresh frequency of the model
  numStates: 7

  #need to overwrite this everytime env gets initialized to the correct number
  #dependent on the lookaheadhorizon length and number of ado cars in an env
  #this is done in get_cfg directly
  numObservations: -1 
  numConstantObservations: 5 # 6 #vels, steer, gas, last actions, rank 
  numActions: 2
  collide: 1
  decimation: 2
  test_mode: False
  collisionstiffness: 280000.0
  
model:
  # SIZE: 0.02 #[px/m]
  # BREAKFORCE: 100
  # ENGINE_POWER_SCALE: 150000000
  # WHEEL_MOMENT_OF_INERTIA_SCALE: 2000
  # FRICTION_LIMIT_SCALE: 10000000
  # OFFTRACK_FRICTION_SCALE: 0.2
  # WHEEL_R_SCALE: 27
  # LENGTH_SCALE: 200
  # MASS_SCALE: 40
  # MOMENT_OF_INERTIA_SCALE: 7.0
  # drag_reduction: 1.3
  M: 3.3 #[kg]
  lf: 0.19 #[m]
  lr: 0.14 #[m]
  Iz:  0.03 #[kg*m^3]
  W: 0.296

  #pajecka coef
  Bf: 0.711
  Br: 1.414
  Cf: 1.414
  Cr: 1.343
  Df: 0.892
  Dr: 0.892
  ACCFORCE: 40 # [N/1]
  MAXVEL: 3

viewer:
  width: 1200  # 1200
  height: 1200  # 1200
  width_tb: 600  # 1200
  height_tb: 600  # 1200
  
  scale: 12.0  # 24.0  # 12.0 #[m/width*px] indicates how wide the window is in pixels
  linethickness: 1
  multiagent: True
  maxAgents: 400
  logEvery: 1  # 10

track:
  #https://github.com/openai/gym/blob/master/gym/envs/box2d/car_racing.py
  SCALE: 40.0  # Track scale
  TRACK_RAD: 420   # Track is heavily morphed circle with this radius
  CHECKPOINTS: 18
  TRACK_DETAIL_STEP: 12 
  TRACK_TURN_RATE: 0.81
  TRACK_WIDTH: 18 
  BORDER: 4 
  BORDER_MIN_COUNT: 3
  verbose: False
  seed: 1
  ccw: True
  draw_centerline: False
  num_tracks: 400

learn:
  use_timeouts: True
  #[posx, posy, theta, vellong, vellat, dtheta, steer]
  resetrand: [0.05, 0.05, 0.1, 0.1, 0.01,  0.1, 0.0]
  reset_tile_rand: 40
  resetgrid: False
  defaultactions: [0., 0.1, 0.0]
  actionscale: [0.3, 0.1, 0.2]
  agent_dropout_prob: 0.2
  distance_obs_cutoff: 100 #[m]

  progressRewardScale: 5.0
  offtrackRewardScale: -5.0
  actionRateRewardScale: 0.1 
  energyRewardScale: 0.00006
  rankRewardScale: 5.0
  collisionRewardScale: -300.0
  horizon: 15
  
  timeout: 25.0 #[s]
  offtrack_reset: 0.8 #[s]
