sim:
  numEnv: 100
  #nuber of racing agents per env
  numAgents: 12
  dt: 0.02 #[s]
  numStates: 7
  numObservations: 5
  numActions: 2
  
  
model:
#Optimization-Based Autonomous Racingof 1:43 Scale RC Cars
#Alexander Liniger, Alexander Domahidi and Manfred Morari
# https://onlinelibrary.wiley.com/doi/abs/10.1002/oca.2123

  m: 0.041 #[kg]
  lf: 0.03 #[m]
  lr: 0.033 #[m]
  Iz:  0.00006 #[kg*m^3]
  w: 0.03

  #pajecka coef
  Bf: 2.58
  Br: 3.38
  Cf: 1.2
  Cr: 1.29
  Df: 0.17
  Dr: 0.1

viewer:
  width: 1500
  height: 1500
  scale: 3.0 #[m/px] indicates how wide the window is in pixels
  linethickness: 1