seed: 1
clip_observations: 1000.0
clip_actions: 4.0

track_cfgs: True

algorithm:
  # clip_param: 0.2
  # entropy_coef: 0.01  # 0.01  # 0.02
  num_learning_epochs: 5  #  5  # 15
  num_mini_batches: 1  # 6 # this is per agent
  learning_rate: 1.e-4  # 5.e-5
  # schedule: adaptive # could be adaptive, linear or fixed
  # gamma: 0.99
  lam: 0.95
  desired_kl: 0.01  # 0.02  # 0.02  # 0.008
  value_loss_coef: 1.0
  use_clipped_value_loss: True
  max_grad_norm: 40.0  # 2.0

runner:
  policy_class_hl_name: MultiTeamBilevelActorCritic  #MultiTeamBilevelDecCritic  # MultiTeamBilevelActorCritic  # BilevelActorCriticAttention  # BilevelActorCritic
  algorithm_class_hl_name: BimaPPO  # BimaDecSARSA  # BimaPPO  # BilevelPPO
  policy_class_ll_name: MultiTeamBilevelActorCritic  # BilevelActorCriticAttention  # BilevelActorCritic
  algorithm_class_ll_name: BimaPPO  # BilevelPPO
  num_steps_per_env_hl: 5  # 20  # 64 # per iteration
  num_steps_per_env_ll: 40  # 40  # 60
  max_iterations: 200  # 1300  # 2400  # 1200 # 500 # number of policy updates
  iter_per_hl: 20  # 20  # 1  # 20
  iter_per_ll: 100  # 200  # 100 # 300  # 200  # 10  # 200
  pretrain_ll_iter: 0  # 200  # 1000
  warmup_hl_iter: 1  # 200
  warmup_hl_ini: 1.0  # 0.5
  population_update_interval: 20  # 100 #number of iterations before the opponent policy is updated
  # logging
  save_interval: 100  # 100  # 50 # check for potential saves every this many iterations
  experiment_name: 'tri_multiagent_blr_hierarchical'  # 'tri_single_blr_hierarchical'
  run_name: ''
  # load and resume
  resume: False
  load_run: -1 # -1 = last run
  checkpoint: -1 # -1 = last saved model
  resume_path: None # updated from load_run and chkpt

policy: 
  actor_hidden_dims: [256, 128]  # [256, 128]
  critic_hidden_dims: [256, 128]  # [256, 128]
  encoder_embed_dims: [64, 64]  # [128]  # [64]
  encoder_attend_dims: [128]
  activation: elu # can be elu, relu, selu, crelu, lrelu, tanh, sigmoid
  init_noise_std: 0.3  # 1.0
  std_per_obs: False
  attentive: True
  encoder_type: attention4  # attention{1, 2, 3, 4}
  teamsize: 2
  numteams: 2
  numcritics: 1
  max_num_old_models: 5
