test: False
trackRaceStatistics: False #makes sim substantially slower
logBehaviorStatistics: True
sim:
  numEnv: 1024
  #number of racing agents per env
  numAgents: 4
  dt: 0.02 #[s] # If using this with TRI dynamics model, this must be 0.02 to match the refresh frequency of the model
  numStates: 7

  #need to overwrite this everytime env gets initialized to the correct number
  #dependent on the lookaheadhorizon length and number of ado cars in an env
  #this is done in get_cfg directly
  numObservations: -1
  numConstantObservations: 8 #vels, rxy, lxy, maxvel, last actions, rank, teamrank
  numConstantObservationsLL: 5  #  5  # goalpos, goalstd, lltime
  numActions: 2
  numActionsHL: 4  # goalpos, goalstd
  collide: 1
  decimation: 4
  test_mode: False
  collisionstiffness: 80.0
  filtercollisionstoego: True  # False
  reset_timeout_only: False

  logBehaviorEvery: 10

model:
  lr: 0.14
  lf: 0.19
  W_coll: 0.35
  L_coll: 0.58
  noise_level: 1.0  # 0.5  # 1.0
  col_decay_time: 0.5
  Iz: 0.03
  max_vel: 3.5
  mass: 3.3
  #gp_noise_scale: 0.01
  Br: 2.482
  Cf: 1.414
  Cr: 1.343
  Df: 0.892
  Dr: 0.892

viewer:
  width: 1200  # 1200
  height: 1200  # 1200
  width_tb: 600  # 1200
  height_tb: 600  # 1200

  scale: 12.0 #[m/width*px] indicates how wide the window is in pixels
  linethickness: 1
  multiagent: True
  maxAgents: 400
  logEvery: 20

track:
  #https://github.com/openai/gym/blob/master/gym/envs/box2d/car_racing.py
  SCALE: 40.0  # Track scale
  TRACK_RAD: 420   # Track is heavily morphed circle with this radius
  CHECKPOINTS: 18
  TRACK_DETAIL_STEP: 12
  TRACK_TURN_RATE: 0.81
  TRACK_WIDTH: 18
  BORDER: 4
  BORDER_MIN_COUNT: 3
  verbose: False
  seed: 1
  ccw: True
  draw_centerline: False
  num_tracks: 20
  track_half_width: 0.7
  track_poly_spacing: 0.15
  
learn:
  steer_ado_with_PPC: True  # True
  iters_ado_with_PPC: 500  # 500  # 5000
  use_timeouts: True
  use_track_curriculum: True
  #[posx, posy, theta, vellong, vellat, dtheta, steer]
  resetrand:  [0.05, 0.05, 0.5, 2.0, 0.01,  0.5, 0.0]  # [0.05, 0.05, 0.9, 4.0, 0.01,  1.1, 0.0]
  #resetrand: [0.00, 0.0, 0., 0.0, 0.0,  0., 0.0]
  reset_tile_rand: 180
  resetgrid: True
  defaultactions: [0.0, 0.1, 0.0]  # [0., 0.5, 0.0]
  actionscale: [0.5, 0.4, 0.2]  # [0.3, 1.0, 0.2]
  defaultactionshl: [0., 0., 0.5, 0.5]
  actionscalehl: [1.0, 1.0, 1.0, 1.0]
  actionsminhl: [4.0, -0.5, 0.1, 0.05]  # [3.0, -0.55, 0.1, 0.1]  # [4.0, -0.55, 0.1, 0.05]  # [3.0, -0.6, 0.1, 0.1]
  actionsmaxhl: [6.0, +0.5, 0.5, 0.3]  # [7.0, +0.55, 0.5, 0.3]  # [6.0, +0.55, 0.5, 0.3]  # [5.0, +0.6, 0.7, 0.7]
  actionsinihl: [+0.0, +0.0, 0.5, 0.5]
  agent_dropout_prob: 0.5
  distance_obs_cutoff: 2.0 #[m]
  race_length_laps: 1

  progressRewardScale: 2.0  # 0.1  # 0.0  # 1.0  # 10.0  # 1.0  # 10.0
  offtrackRewardScale: -1.0  # -0.2  # -0.2  # -1.0  # -0.1  # -0.1
  actionRateRewardScale: -0.1  # -0.01  # -0.1
  rankRewardScale: 1.0  # 1.0  # 5.0  # 5.0  # 1.0
  collisionRewardScale: -1.0  #-0.2  # -0.02  # -0.2
  accRewardScale: -0.1  # -0.5
  goalRewardScale: 0.0  # 1.0  # 1.0  # 1.0  # 5.0
  horizon: 12  # 12  # 15

  episode_length_ll: 20  # 20  # low-level steps in high-level step

  timeout: 24.0  # 25.0 #[s]
  offtrack_reset: 0.5  # 1.0  # 0.8 #[s]
  obs_noise_lvl: 0.005  # 1.0  # 1.0  # FIXME: change back?
