ACCFORCE: 40.0
Iz: 0.03
MAXVEL: 1.0
accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
angular_smoothing: 0.0002
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: null
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
dropout_p: 0.5
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
feedforward_tire_model: false
filter_data: false
fix_car_params: false
flush_logs_every_n_steps: null
gpus: 1
gradient_clip_algorithm: null
gradient_clip_val: null
heading_loss_multiplier: 1.0
hidden_size: 4
hybrid: false
improved_integration: true
initializer_size: 32
ipus: null
jit_compile_dynamics: false
kinematic: true
lf: 0.19
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
linear_smoothing: 2.0e-05
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 0.14
lstm: false
mass: 3.3
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
model_save_metric: val_position_loss
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
past_steps: 50
plugins: null
position_loss: true
precision: 32
prediction_steps: 150
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
raw_position: true
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
roll_scale: 1.0
roll_stability_loss_scale: 0.0
roll_stability_time_constant: 100000.0
steering_scale_offset: false
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
tpu_cores: null
track_grad_norm: -1
train_batch_size: 128
train_data:
- ../tri_dynamics_data/train/racecar_2_2021-12-07-17-03-29.json
- ../tri_dynamics_data/train/racecar_2_2021-12-07-17-00-48.json
use_dropout: false
val_check_interval: 1.0
val_data:
- ../tri_dynamics_data/val/cut_val_3.json
velocity_loss: false
weights_save_path: null
weights_summary: top
